db:
  image: postgres:9.4
  ports:
    - "5432"
web:
  build: .
  command: bash -c "rm -f tmp/pids/server.pid && foreman start -f Procfile.dev"
  volumes:
    - .:/app
  stdin_open: true
  ports:
    - "3000:3000"
  links:
    - db
