default: &default
  adapter: postgresql
  encoding: utf8
  min_messages: warning
  pool: 5
  host: db
  username: postgres

development:
  <<: *default
  database: hsmr_development

test:
    <<: *default
    pool: 4
    database: hsmr_test
